### ISSUE TITLE
请问，可以增加个批量下载的功能吗？

### ISSUE THREAD

**Issue by mpco** [animalize/tz2txt#1]
比如，将网址按照每行一个放在一个文本里，批量下载并将文件命名为帖子的标题

**Comment by animalize** [comment]
tz2txt有命令行的操作方式，可以自己写一个小脚本，调用tz2txt批量下载。

想自动重命名就不行了，得自己写相关代码。不过因为输出文件的格式是固定的，所以也不算难。
